/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school_managment_system;

import java.sql.CallableStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author DHEERAJ K'S PC
 */
public class Certificate extends javax.swing.JFrame {

    /**
     * Creates new form Certificate
     */
    int id;
    String c_id,t_year;
    Database db;
    CallableStatement mystmt;
    public Certificate(int id,String c_id,String t_year) {
        this.id=id;
        this.c_id=c_id;
        this.t_year=t_year;
        db=new Database();
        mystmt=null;
        initComponents();
        this.setLocationRelativeTo(null);
        showCertificate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelMin = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelFirstName13 = new javax.swing.JLabel();
        jLabelStudentId = new javax.swing.JLabel();
        jLabelFirstName3 = new javax.swing.JLabel();
        jLabel_Sname = new javax.swing.JLabel();
        jLabelBirthDate = new javax.swing.JLabel();
        jLabel_BirthDate = new javax.swing.JLabel();
        jLabelFirstName11 = new javax.swing.JLabel();
        jLabelClass = new javax.swing.JLabel();
        jLabelFirstName9 = new javax.swing.JLabel();
        jLabel_Gender = new javax.swing.JLabel();
        jLabel_L_School = new javax.swing.JLabel();
        jLabelFirstName5 = new javax.swing.JLabel();
        jLabel_F_Name = new javax.swing.JLabel();
        jLabelFirstName7 = new javax.swing.JLabel();
        jLabelContact = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jLabelBirthDate2 = new javax.swing.JLabel();
        jLabel_Tyear = new javax.swing.JLabel();
        jLabelFirstName41 = new javax.swing.JLabel();
        jLabel_t_sum = new javax.swing.JLabel();
        jLabel_o_sum = new javax.swing.JLabel();
        jLabelFirstName42 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelFirstName58 = new javax.swing.JLabel();
        jLabelFirstName56 = new javax.swing.JLabel();
        jLabel_G = new javax.swing.JLabel();
        jLabel_P = new javax.swing.JLabel();
        jLabelAddress1 = new javax.swing.JLabel();
        jLabel_Address = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton_Print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(42, 62, 80));

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText(" -");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText(" X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(697, Short.MAX_VALUE)
                    .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(9, 9, 9)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFirstName13.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName13.setText("Studetn ID:");
        jPanel3.add(jLabelFirstName13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 116, -1));

        jLabelStudentId.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelStudentId.setText("1001");
        jPanel3.add(jLabelStudentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 58, -1));

        jLabelFirstName3.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName3.setText("First Name:");
        jPanel3.add(jLabelFirstName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel_Sname.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel_Sname.setText("Dheeraj Parkash");
        jPanel3.add(jLabel_Sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabelBirthDate.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelBirthDate.setText("Birth Date:");
        jPanel3.add(jLabelBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel_BirthDate.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel_BirthDate.setText("2020-01-01");
        jPanel3.add(jLabel_BirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        jLabelFirstName11.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName11.setText("Class:");
        jPanel3.add(jLabelFirstName11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jLabelClass.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelClass.setText("Two");
        jPanel3.add(jLabelClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 63, -1));

        jLabelFirstName9.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName9.setText("Gender:");
        jPanel3.add(jLabelFirstName9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        jLabel_Gender.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel_Gender.setText(" Male");
        jPanel3.add(jLabel_Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 63, -1));

        jLabel_L_School.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel_L_School.setText("Cambridge Public Higehr Secondary School");
        jPanel3.add(jLabel_L_School, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, 30));

        jLabelFirstName5.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName5.setText("Father's Name:");
        jPanel3.add(jLabelFirstName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 145, -1));

        jLabel_F_Name.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel_F_Name.setText("Surya Parkash");
        jPanel3.add(jLabel_F_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 152, -1));

        jLabelFirstName7.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName7.setText("Contact:");
        jPanel3.add(jLabelFirstName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        jLabelContact.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelContact.setText("0333-1234567");
        jPanel3.add(jLabelContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 147, 30));

        jLabelAddress.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelAddress.setText("Last  School:");
        jPanel3.add(jLabelAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabelBirthDate2.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelBirthDate2.setText("Term Year:");
        jPanel3.add(jLabelBirthDate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        jLabel_Tyear.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel_Tyear.setText("2020/2021");
        jPanel3.add(jLabel_Tyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        jLabelFirstName41.setBackground(new java.awt.Color(0, 0, 0));
        jLabelFirstName41.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName41.setText("Total Marks");
        jPanel3.add(jLabelFirstName41, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        jLabel_t_sum.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_t_sum.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel_t_sum.setText("600");
        jPanel3.add(jLabel_t_sum, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

        jLabel_o_sum.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_o_sum.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel_o_sum.setText("600");
        jPanel3.add(jLabel_o_sum, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, -1, -1));

        jLabelFirstName42.setBackground(new java.awt.Color(0, 0, 0));
        jLabelFirstName42.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName42.setText("Obtained Marks:");
        jPanel3.add(jLabelFirstName42, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 730, 40));

        jLabelFirstName58.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFirstName58.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName58.setText("Percentage:");
        jPanel3.add(jLabelFirstName58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        jLabelFirstName56.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFirstName56.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName56.setText("Grade:");
        jPanel3.add(jLabelFirstName56, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        jLabel_G.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_G.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel_G.setText("A+");
        jPanel3.add(jLabel_G, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        jLabel_P.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_P.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel_P.setText("75%");
        jPanel3.add(jLabel_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        jLabelAddress1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelAddress1.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelAddress1.setText("Address:  ");
        jPanel3.add(jLabelAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, 35));

        jLabel_Address.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_Address.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel_Address.setText("Sukkur iba univetrsity");
        jPanel3.add(jLabel_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 510, 35));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school_managment_system/Images/Certification.PNG"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 740, 590));

        jPanel4.setBackground(new java.awt.Color(42, 62, 80));

        jButton_Print.setBackground(new java.awt.Color(34, 167, 240));
        jButton_Print.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Print.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Print.setText("Print");
        jButton_Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(610, Short.MAX_VALUE)
                .addComponent(jButton_Print, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Print, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void showCertificate(){
        try {
            mystmt=db.con.prepareCall("{call generate_Certificate(?,?,?)}");
            mystmt.setInt(1,this.id);
            mystmt.setString(2,this.c_id);
            mystmt.setString(3,this.t_year);
            boolean hasresult=mystmt.execute();
                if(hasresult){
                    db.rs=mystmt.getResultSet();
                    if(db.rs.next()){
                        jLabelStudentId.setText(String.valueOf(db.rs.getInt("id")));
                        jLabel_Sname.setText(db.rs.getString("s_name"));
                        jLabel_Gender.setText(db.rs.getString("gender"));
                        jLabel_BirthDate.setText(db.rs.getString("s_name"));
                        jLabel_Tyear.setText(db.rs.getString("birth_date"));
                        jLabel_L_School.setText(db.rs.getString("last_school"));
                        jLabel_F_Name.setText(db.rs.getString("name"));
                        jLabelContact.setText(db.rs.getString("contact"));
                        jLabelClass.setText(db.rs.getString("c_id"));
                        jLabel_t_sum.setText(String.valueOf(db.rs.getInt("t_marks")));
                        jLabel_o_sum.setText(String.valueOf(db.rs.getInt("o_marks")));
                        jLabel_G.setText(db.rs.getString("grade"));
                        jLabel_Address.setText(db.rs.getString("address"));
                        jLabel_P.setText(String.valueOf(db.rs.getInt("percentage")));
                    }
                }
        } catch (SQLException ex) {
            Logger.getLogger(Certificate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jButton_PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PrintActionPerformed
            
        Selection sc=new Selection();
        sc.setVisible(true);
        sc.pack();
        sc.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton_PrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Certificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Certificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Certificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Certificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Certificate(0,"","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Print;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelAddress1;
    private javax.swing.JLabel jLabelBirthDate;
    private javax.swing.JLabel jLabelBirthDate2;
    private javax.swing.JLabel jLabelClass;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelContact;
    private javax.swing.JLabel jLabelFirstName11;
    private javax.swing.JLabel jLabelFirstName13;
    private javax.swing.JLabel jLabelFirstName3;
    private javax.swing.JLabel jLabelFirstName41;
    private javax.swing.JLabel jLabelFirstName42;
    private javax.swing.JLabel jLabelFirstName5;
    private javax.swing.JLabel jLabelFirstName56;
    private javax.swing.JLabel jLabelFirstName58;
    private javax.swing.JLabel jLabelFirstName7;
    private javax.swing.JLabel jLabelFirstName9;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelStudentId;
    private javax.swing.JLabel jLabel_Address;
    private javax.swing.JLabel jLabel_BirthDate;
    private javax.swing.JLabel jLabel_F_Name;
    private javax.swing.JLabel jLabel_G;
    private javax.swing.JLabel jLabel_Gender;
    private javax.swing.JLabel jLabel_L_School;
    private javax.swing.JLabel jLabel_P;
    private javax.swing.JLabel jLabel_Sname;
    private javax.swing.JLabel jLabel_Tyear;
    private javax.swing.JLabel jLabel_o_sum;
    private javax.swing.JLabel jLabel_t_sum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
