/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school_managment_system;

import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author DHEERAJ K'S PC
 */
public class employee_details extends javax.swing.JFrame {

    /**
     * Creates new form employee_details
     */
    int e_id;
    String sql;
    Database db;
    public employee_details(int id) {
        initComponents();
        e_id=id;
        sql="";
        db=new Database();
        this.setLocationRelativeTo(null);
        this.dispData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton_Edit = new javax.swing.JButton();
        jLabelLastName = new javax.swing.JLabel();
        jLabelBirthDate = new javax.swing.JLabel();
        jLabelFirstName2 = new javax.swing.JLabel();
        jLabelFirstName3 = new javax.swing.JLabel();
        jLabelFirstName7 = new javax.swing.JLabel();
        jLabelAddress1 = new javax.swing.JLabel();
        jLabelFirstName8 = new javax.swing.JLabel();
        jLabelFirstName = new javax.swing.JLabel();
        jLabel_Last_Name = new javax.swing.JLabel();
        jLabelFirstName9 = new javax.swing.JLabel();
        jLabelGender = new javax.swing.JLabel();
        jLabel_J_date = new javax.swing.JLabel();
        jLabelFirstName11 = new javax.swing.JLabel();
        jLabel_designation = new javax.swing.JLabel();
        jLabelFirstName13 = new javax.swing.JLabel();
        jLabel_e_id = new javax.swing.JLabel();
        jLabelContact = new javax.swing.JLabel();
        jLabel_Cnic = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jLabelFirstName15 = new javax.swing.JLabel();
        jLabeSalary = new javax.swing.JLabel();
        jButtonPrint = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelMin = new javax.swing.JLabel();
        jLabelRegister = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(42, 62, 80));

        jButton_Edit.setBackground(new java.awt.Color(242, 38, 19));
        jButton_Edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Edit.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Edit.setText("Edit");
        jButton_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditActionPerformed(evt);
            }
        });

        jLabelLastName.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelLastName.setForeground(new java.awt.Color(236, 240, 241));
        jLabelLastName.setText("Last Name:");

        jLabelBirthDate.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelBirthDate.setForeground(new java.awt.Color(236, 240, 241));
        jLabelBirthDate.setText("Joining Date:");

        jLabelFirstName2.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName2.setForeground(new java.awt.Color(236, 240, 241));
        jLabelFirstName2.setText("Email:");

        jLabelFirstName3.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName3.setForeground(new java.awt.Color(236, 240, 241));
        jLabelFirstName3.setText("First Name:");

        jLabelFirstName7.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName7.setForeground(new java.awt.Color(236, 240, 241));
        jLabelFirstName7.setText("Contact:");

        jLabelAddress1.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelAddress1.setForeground(new java.awt.Color(236, 240, 241));
        jLabelAddress1.setText("Address:");

        jLabelFirstName8.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName8.setForeground(new java.awt.Color(236, 240, 241));
        jLabelFirstName8.setText("CNIC:");

        jLabelFirstName.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName.setForeground(new java.awt.Color(236, 240, 241));
        jLabelFirstName.setText("Dheeraj");

        jLabel_Last_Name.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel_Last_Name.setForeground(new java.awt.Color(236, 240, 241));
        jLabel_Last_Name.setText("Parkash");

        jLabelFirstName9.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName9.setForeground(new java.awt.Color(236, 240, 241));
        jLabelFirstName9.setText("Gender:");

        jLabelGender.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelGender.setForeground(new java.awt.Color(236, 240, 241));
        jLabelGender.setText("Male");

        jLabel_J_date.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel_J_date.setForeground(new java.awt.Color(236, 240, 241));
        jLabel_J_date.setText("2020-01-01");

        jLabelFirstName11.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName11.setForeground(new java.awt.Color(236, 240, 241));
        jLabelFirstName11.setText("Designation:");

        jLabel_designation.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel_designation.setForeground(new java.awt.Color(236, 240, 241));
        jLabel_designation.setText("Teacher");

        jLabelFirstName13.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName13.setForeground(new java.awt.Color(236, 240, 241));
        jLabelFirstName13.setText("Employee ID:");

        jLabel_e_id.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel_e_id.setForeground(new java.awt.Color(236, 240, 241));
        jLabel_e_id.setText("1001");

        jLabelContact.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelContact.setForeground(new java.awt.Color(236, 240, 241));
        jLabelContact.setText("0333-1234567");

        jLabel_Cnic.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel_Cnic.setForeground(new java.awt.Color(236, 240, 241));
        jLabel_Cnic.setText("1234-67891234-5");

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(236, 240, 241));
        jLabelEmail.setText("abcdefg@gamil.com");

        jLabelAddress.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelAddress.setForeground(new java.awt.Color(236, 240, 241));
        jLabelAddress.setText("Sukkur iba univetrsity");

        jLabelFirstName15.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName15.setForeground(new java.awt.Color(236, 240, 241));
        jLabelFirstName15.setText("Salary:");

        jLabeSalary.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabeSalary.setForeground(new java.awt.Color(236, 240, 241));
        jLabeSalary.setText("1000000");

        jButtonPrint.setBackground(new java.awt.Color(34, 167, 240));
        jButtonPrint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPrint.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPrint.setText("Print");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jButton_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelFirstName13)
                                    .addComponent(jLabelFirstName3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelFirstName11)
                                    .addComponent(jLabelFirstName9)
                                    .addComponent(jLabelFirstName8)
                                    .addComponent(jLabelFirstName2)
                                    .addComponent(jLabelAddress1))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelFirstName)
                                .addGap(44, 44, 44)
                                .addComponent(jLabelLastName)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel_Last_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_e_id, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel_Cnic, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabelFirstName7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelContact, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelEmail)
                            .addComponent(jLabelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel_designation)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelFirstName15))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelGender)
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabelBirthDate)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_J_date)
                                    .addComponent(jLabeSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirstName13)
                    .addComponent(jLabel_e_id))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelFirstName3)
                        .addComponent(jLabelFirstName))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelLastName)
                        .addComponent(jLabel_Last_Name)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelBirthDate)
                                .addComponent(jLabel_J_date))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelFirstName9)
                                .addComponent(jLabelGender)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFirstName15)
                            .addComponent(jLabeSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFirstName11)
                            .addComponent(jLabel_designation))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelFirstName8)
                        .addComponent(jLabelFirstName7)
                        .addComponent(jLabelContact, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_Cnic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirstName2)
                    .addComponent(jLabelEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddress1)
                    .addComponent(jLabelAddress))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText(" -");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        jLabelRegister.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelRegister.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegister.setText("Employee Details");

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText(" X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jLabelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(321, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(537, Short.MAX_VALUE)
                    .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(9, 9, 9)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMin, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelClose, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void dispData(){
        sql="SELECT * FROM employees WHERE id="+e_id;
        
        try {
            db.rs = db.stmt.executeQuery(sql);
            boolean next = db.rs.next();
            if(next){
                jLabel_e_id.setText(String.valueOf(db.rs.getInt("id")));
                jLabelFirstName.setText(db.rs.getString("first_name"));
                jLabel_Last_Name.setText(db.rs.getString("last_name"));
                jLabelGender.setText(db.rs.getString("gender"));
                jLabel_J_date.setText(db.rs.getString("joining_date"));
                jLabel_designation.setText(db.rs.getString("designation"));
                jLabel_Cnic.setText(db.rs.getString("cnic"));
                jLabeSalary.setText(db.rs.getString("salary"));
                jLabelContact.setText(db.rs.getString("contact"));
                jLabelEmail.setText(db.rs.getString("email"));
                jLabelAddress.setText(db.rs.getString("address"));
            }
            else{
                JOptionPane.showMessageDialog(this, "Something got wrong");
            }
            
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    private void jButton_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditActionPerformed
        
        Update_Employee_Details ued=new Update_Employee_Details(e_id);
        ued.setVisible(true);
        ued.pack();
        ued.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton_EditActionPerformed

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        Selection rep=new Selection();
        rep.setVisible(true);
        rep.pack();
        rep.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee_details(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButton_Edit;
    private javax.swing.JLabel jLabeSalary;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelAddress1;
    private javax.swing.JLabel jLabelBirthDate;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelContact;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelFirstName11;
    private javax.swing.JLabel jLabelFirstName13;
    private javax.swing.JLabel jLabelFirstName15;
    private javax.swing.JLabel jLabelFirstName2;
    private javax.swing.JLabel jLabelFirstName3;
    private javax.swing.JLabel jLabelFirstName7;
    private javax.swing.JLabel jLabelFirstName8;
    private javax.swing.JLabel jLabelFirstName9;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelRegister;
    private javax.swing.JLabel jLabel_Cnic;
    private javax.swing.JLabel jLabel_J_date;
    private javax.swing.JLabel jLabel_Last_Name;
    private javax.swing.JLabel jLabel_designation;
    private javax.swing.JLabel jLabel_e_id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
