/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school_managment_system;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author DHEERAJ K'S PC
 */
public class Student_details extends javax.swing.JFrame {

    /**
     * Creates new form Sudent_details
     */
    int s_id;
    String first_name,last_name,p_id,gender,birth_date,c_class,last_school,name,cnic,contact,email,address,t_year;
    String sql;
    Database db;
    S_Details sd;
    public Student_details(int id) {
        initComponents();
        s_id=id;
        sql="";
        db=new Database();
        this.setLocationRelativeTo(null);
        this.current_class();
        this.dispData();
    }
    private void current_class(){
        sql="SELECT c_id FROM studentclass where s_id="+s_id+" ORDER BY c_id DESC limit 1";
        try {
            db.rs=db.stmt.executeQuery(sql);
            boolean next = db.rs.next();
            if(next){
                this.c_class=db.rs.getString("c_id");
            }
            else{
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Student_details.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonEdit = new javax.swing.JButton();
        jLabelLastName = new javax.swing.JLabel();
        jLabelBirthDate = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jLabelFirstName2 = new javax.swing.JLabel();
        jLabelFirstName3 = new javax.swing.JLabel();
        jLabelFirstName5 = new javax.swing.JLabel();
        jLabelFirstName7 = new javax.swing.JLabel();
        jLabelAddress1 = new javax.swing.JLabel();
        jButtonPrint = new javax.swing.JButton();
        jLabelFirstName8 = new javax.swing.JLabel();
        jLabelFirstName = new javax.swing.JLabel();
        jLabelLastname = new javax.swing.JLabel();
        jLabelFirstName9 = new javax.swing.JLabel();
        jLabelGender = new javax.swing.JLabel();
        jLabelBirthDate1 = new javax.swing.JLabel();
        jLabelFirstName11 = new javax.swing.JLabel();
        jLabelClass = new javax.swing.JLabel();
        jLabel_L_School = new javax.swing.JLabel();
        jLabelFirstName13 = new javax.swing.JLabel();
        jLabelStudentId = new javax.swing.JLabel();
        jLabelFirstName15 = new javax.swing.JLabel();
        jLabel_P_id = new javax.swing.JLabel();
        jLabelContact = new javax.swing.JLabel();
        jLabel_F_Name = new javax.swing.JLabel();
        jLabelCnic = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelAddress4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelMin = new javax.swing.JLabel();
        jLabelRegister = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(42, 62, 80));

        jButtonEdit.setBackground(new java.awt.Color(242, 38, 19));
        jButtonEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEdit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jLabelLastName.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelLastName.setForeground(new java.awt.Color(236, 240, 241));
        jLabelLastName.setText("Last Name:");

        jLabelBirthDate.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelBirthDate.setForeground(new java.awt.Color(236, 240, 241));
        jLabelBirthDate.setText("Birth Date:");

        jLabelAddress.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelAddress.setForeground(new java.awt.Color(236, 240, 241));
        jLabelAddress.setText("Last Attendent School:");

        jLabelFirstName2.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName2.setForeground(new java.awt.Color(236, 240, 241));
        jLabelFirstName2.setText("Email:");

        jLabelFirstName3.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName3.setForeground(new java.awt.Color(236, 240, 241));
        jLabelFirstName3.setText("First Name:");

        jLabelFirstName5.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName5.setForeground(new java.awt.Color(236, 240, 241));
        jLabelFirstName5.setText("Father's Name:");

        jLabelFirstName7.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName7.setForeground(new java.awt.Color(236, 240, 241));
        jLabelFirstName7.setText("Contact:");

        jLabelAddress1.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelAddress1.setForeground(new java.awt.Color(236, 240, 241));
        jLabelAddress1.setText("Address:  ");

        jButtonPrint.setBackground(new java.awt.Color(34, 167, 240));
        jButtonPrint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPrint.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPrint.setText("Print");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        jLabelFirstName8.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName8.setForeground(new java.awt.Color(236, 240, 241));
        jLabelFirstName8.setText("CNIC:");

        jLabelFirstName.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName.setForeground(new java.awt.Color(236, 240, 241));
        jLabelFirstName.setText("Dheeraj");

        jLabelLastname.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelLastname.setForeground(new java.awt.Color(236, 240, 241));
        jLabelLastname.setText("Parkash");

        jLabelFirstName9.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName9.setForeground(new java.awt.Color(236, 240, 241));
        jLabelFirstName9.setText("Gender:");

        jLabelGender.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelGender.setForeground(new java.awt.Color(236, 240, 241));
        jLabelGender.setText(" Male");

        jLabelBirthDate1.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelBirthDate1.setForeground(new java.awt.Color(236, 240, 241));
        jLabelBirthDate1.setText("2020-01-01");

        jLabelFirstName11.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName11.setForeground(new java.awt.Color(236, 240, 241));
        jLabelFirstName11.setText("Class:");

        jLabelClass.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelClass.setForeground(new java.awt.Color(236, 240, 241));
        jLabelClass.setText("Two");

        jLabel_L_School.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel_L_School.setForeground(new java.awt.Color(236, 240, 241));
        jLabel_L_School.setText("Cambridge Public Higehr Secondary School");

        jLabelFirstName13.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName13.setForeground(new java.awt.Color(236, 240, 241));
        jLabelFirstName13.setText("Studetn ID:");

        jLabelStudentId.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelStudentId.setForeground(new java.awt.Color(236, 240, 241));
        jLabelStudentId.setText("1001");

        jLabelFirstName15.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelFirstName15.setForeground(new java.awt.Color(236, 240, 241));
        jLabelFirstName15.setText("Parent ID:");

        jLabel_P_id.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel_P_id.setForeground(new java.awt.Color(236, 240, 241));
        jLabel_P_id.setText("1003");

        jLabelContact.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelContact.setForeground(new java.awt.Color(236, 240, 241));
        jLabelContact.setText("0333-1234567");

        jLabel_F_Name.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel_F_Name.setForeground(new java.awt.Color(236, 240, 241));
        jLabel_F_Name.setText("Surya Parkash");

        jLabelCnic.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelCnic.setForeground(new java.awt.Color(236, 240, 241));
        jLabelCnic.setText("1234-67891234-5");

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(236, 240, 241));
        jLabelEmail.setText("abcdefg@gamil.com");

        jLabelAddress4.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelAddress4.setForeground(new java.awt.Color(236, 240, 241));
        jLabelAddress4.setText("Sukkur iba univetrsity");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_L_School))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFirstName13, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelBirthDate)
                                .addComponent(jLabelFirstName3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabelLastName))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelBirthDate1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelFirstName11)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelClass, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelFirstName9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelFirstName15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_P_id, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelFirstName5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_F_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelFirstName7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelContact, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabelFirstName8)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabelCnic, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabelFirstName2)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelAddress1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelAddress4, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirstName13)
                    .addComponent(jLabelStudentId))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirstName3)
                    .addComponent(jLabelFirstName)
                    .addComponent(jLabelLastName)
                    .addComponent(jLabelFirstName9)
                    .addComponent(jLabelGender)
                    .addComponent(jLabelLastname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelBirthDate)
                        .addComponent(jLabelBirthDate1))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelFirstName11)
                        .addComponent(jLabelClass)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_L_School, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelFirstName15)
                                    .addComponent(jLabel_P_id))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelFirstName5))
                            .addComponent(jLabel_F_Name, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFirstName7)
                            .addComponent(jLabelContact, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFirstName8)
                            .addComponent(jLabelCnic))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFirstName2)
                            .addComponent(jLabelEmail))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAddress4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText(" -");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        jLabelRegister.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelRegister.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegister.setText("Student Details");

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText(" X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jLabelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(421, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(637, Short.MAX_VALUE)
                    .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(9, 9, 9)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMin, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelClose, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void dispData(){
        sql="SELECT s.*,p.* FROM students s NATURAL JOIN parent p WHERE s_id="+s_id;
        
        try {
            db.rs = db.stmt.executeQuery(sql);
            boolean next = db.rs.next();
            if(next){
                this.first_name=db.rs.getString("first_name");
                this.last_name=db.rs.getString("last_name");
                this.p_id=String.valueOf(db.rs.getInt("p_id"));
                this.gender=db.rs.getString("gender");
                this.birth_date=db.rs.getString("birth_date");
                this.last_school=db.rs.getString("last_school");
                this.name=db.rs.getString("name");
                this.cnic=db.rs.getString("cnic");
                this.contact=db.rs.getString("contact");
                this.email=db.rs.getString("email");
                this.address=db.rs.getString("address");
                
                jLabelStudentId.setText(String.valueOf(this.s_id));
                jLabelFirstName.setText(this.first_name);
                jLabelLastname.setText(this.last_name);
                jLabel_P_id.setText(this.p_id);
                jLabelGender.setText(this.gender);
                jLabelBirthDate1.setText(this.birth_date);
                jLabelClass.setText(this.c_class);
                jLabel_L_School.setText(this.last_school);
                jLabel_F_Name.setText(this.name);
                jLabelCnic.setText(this.cnic);
                jLabelContact.setText(this.contact);
                jLabelEmail.setText(this.email);
                jLabelAddress4.setText(this.address);
            }
            
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        sd=new S_Details(s_id,first_name,last_name,p_id,gender,birth_date,c_class,last_school,name,cnic,contact,email,address);
        Update_Student_Details usd=new Update_Student_Details(sd);
        usd.setVisible(true);
        usd.pack();
        usd.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        Selection rep=new Selection();
        rep.setVisible(true);
        rep.pack();
        rep.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_details(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelAddress1;
    private javax.swing.JLabel jLabelAddress4;
    private javax.swing.JLabel jLabelBirthDate;
    private javax.swing.JLabel jLabelBirthDate1;
    private javax.swing.JLabel jLabelClass;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelCnic;
    private javax.swing.JLabel jLabelContact;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelFirstName11;
    private javax.swing.JLabel jLabelFirstName13;
    private javax.swing.JLabel jLabelFirstName15;
    private javax.swing.JLabel jLabelFirstName2;
    private javax.swing.JLabel jLabelFirstName3;
    private javax.swing.JLabel jLabelFirstName5;
    private javax.swing.JLabel jLabelFirstName7;
    private javax.swing.JLabel jLabelFirstName8;
    private javax.swing.JLabel jLabelFirstName9;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelLastname;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelRegister;
    private javax.swing.JLabel jLabelStudentId;
    private javax.swing.JLabel jLabel_F_Name;
    private javax.swing.JLabel jLabel_L_School;
    private javax.swing.JLabel jLabel_P_id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
